<?php

namespace App\Constants;

class Errors
{
    const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';
    const REQUEST_FAILED = 'REQUEST_FAILED';
    const ACTION_NOT_SUPPORTED = 'ACTION_NOT_SUPPORTED';
    const UNAUTHORIZED = 'UNAUTHORIZED';
    const VALIDATION_FALIED = 'VALIDATION_FAILED';
    const METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED';
    const ENDPOINT_NOT_FOUND = 'ENDPOINT_NOT_FOUND';
    const RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND';
}